### ISSUE TITLE
Failures when I tried running Test_2al5

### ISSUE THREAD

**Issue by gaoshan2006** [jenniening/deltaVinaXGB#10]
Hi Jenniening,

Thanks for your sharing this interesting working!  As a novice, I first tried to run the example in the package.
  "python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average "    I run on my linux server.  However, the failure was blocking me, which looks like :

.............
Protein with water molecules:2al5_protein_all.pdb
Finish Input Preparation
No Consideration of Water
No Optimized Ligand
C
Finish Vina
 has no corresponding radius valuenfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * [0-9]*H.* 15
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * F[1-9].* 40
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * CL[1-9].* 41
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * BR[1-9].* 42
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * I[1-9].* 43
 has no corresponding radius value /nfs/software_local/delta/deltaVinaXGB/DXGB/atmtypenumbers entry  * FE2 25
....................................
1.1
SASA failed
Traceback (most recent call last):
  File "run_DXGB.py", line 103, in <module>
    main()
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run_DXGB.py", line 43, in main
    run_features(datadir, pdbid, water_type = water, opt_type = opt, rewrite = rewrite, feature_type = featuretype)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 599, in run_features
    feature_calculation_ligand(datadir, pdbid, inlig_pdb, inlig_rdkit, inpro_pro, water_type, opt_type, rewrite, feature_type)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 528, in feature_calculation_ligand
    run_SASA_features(datadir, i, fn, inpro, inlig)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 383, in run_SASA_features
    cal_SASA(out_SASA,fn,inlig,inpro,datadir)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_sasa.py", line 26, in cal_SASA
    sasa_features = sasa(datadir,pro,lig)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 219, in __init__
    self.rawdata, self.rawdata_pro, self.rawdata_lig, self.sasa, self.sasa_pro, self.sasa_lig = featureSASA( self.datadir, self.prot, self.lig)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 149, in featureSASA
    df,df_pro,df_lig = runMSMS(inprot, inlig, datadir)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 103, in runMSMS
    tmp1 = np.genfromtxt('p_sa.area', skip_header=1)[:,2]
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1793, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: p_sa.area not found.

I have checked the msms  reference for  [issue #6](https://github.com/jenniening/deltaVinaXGB/issues/6),   It looks the solution in issue #6 does not work for my issue.  Could you give me some help please ? Thanks a lot !

**Comment by gaoshan2006** [comment]
Besides the issue as above, which should be from SASA failure, I guess.  When I specified the --featuretype  as "Vina"  ( it could exclude "SASA" ? ) ,  I met another failure as well .

 python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average --featuretype Vina

.................
Finish Vina
Use previous calculated SASA
Use previous calculated Ion
Use previous calculated dE
Traceback (most recent call last):
  File "run_DXGB.py", line 103, in <module>
    main()
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run_DXGB.py", line 43, in main
    run_features(datadir, pdbid, water_type = water, opt_type = opt, rewrite = rewrite, feature_type = featuretype)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 599, in run_features
    feature_calculation_ligand(datadir, pdbid, inlig_pdb, inlig_rdkit, inpro_pro, water_type, opt_type, rewrite, feature_type)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 547, in feature_calculation_ligand
    combine(datadir,i)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/combine_data.py", line 48, in combine
    f = read_file(Vina58,SASA,dE,Water,Ion)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/combine_data.py", line 29, in read_file
    f_ion = pd.read_csv(Ion,dtype={"pdb":str})
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/hadoop/.conda/envs/DXGB/lib/python3.7/site-packages/pandas/io/common.py", line 706, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/software_local/delta/deltaVinaXGB/Test_2al5/Num_Ions.csv'


I am puzzled by these failures. Maybe what steps did I do wrong?  I have to reach out for your help.  
Thanks again !

**Comment by gaoshan2006** [comment]
I got the root cause. The stomtypenumber  file could not be parsed by  pdb_to_xyzr correctly, which maybe is relevant with the shell environment --- I am using Bash shell.  After I did a bit of changes in pdb_to_xyzr shell file, the issue could be resolved.  Thanks a lot !
