### ISSUE TITLE
No such file or directory: 'score_v1.txt' when running tutorial provided commands

### ISSUE THREAD

**Issue by yanz-24** [jenniening/deltaVinaXGB#4]
Dear jenniening,

Thank you for the tool. I installed all the necessary dependencies and I was trying to run the command provided in the [tutorial](https://yzhang.hpc.nyu.edu/DeltaVina/tutorial.html)
```
python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average 
```
 and I received the following error messages :
```
(DXGB) [yrui@ibet DXGB]$         python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average 
pdb index: 2al5
file directory: /home/deltaVinaXGB/Test_2al5
feature will be calculated:all
output filename : score.csv
1 molecule converted
Ligand for conformation stability:2al5_ligand.mol2
Ligand for Vina, SASA, BA, ION:2al5_ligand_rename.pdb
Protein without water molecules:2al5_protein.pdb
Protein with water molecules:2al5_protein_all.pdb
Finish Input Preparation
No Consideration of Water
No Optimized Ligand
C
sh: /home/mgltools_x86_64Linux2_1.5.6//bin/python: No such file or directory
sh: /home/mgltools_x86_64Linux2_1.5.6//bin/python: No such file or directory
sh: /home/vina4dv/build/linux/release//vina: No such file or directory
Traceback (most recent call last):
  File "run_DXGB.py", line 103, in <module>
    main()
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run_DXGB.py", line 43, in main
    run_features(datadir, pdbid, water_type = water, opt_type = opt, rewrite = rewrite, feature_type = featuretype)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 599, in run_features
    feature_calculation_ligand(datadir, pdbid, inlig_pdb, inlig_rdkit, inpro_pro, water_type, opt_type, rewrite, feature_type)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 522, in feature_calculation_ligand
    run_Vina_features(datadir, i, fn, inpro, inlig)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 364, in run_Vina_features
    featureVina(outfile, fn, inpro, inlig, datadir)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_vina58.py", line 58, in featureVina
    vinalist = runVina(fn,protpdbqt,ligpdbqt)
  File "/home/.conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_vina58.py", line 15, in runVina
    for lines in fileinput.input("score_v1.txt"):
  File "/home/.conda/envs/DXGB/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/home/.conda/envs/DXGB/lib/python3.7/fileinput.py", line 364, in _readline
    self._file = open(self._filename, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: 'score_v1.txt'
```
I would like to know how to solve this issue?

Thank you in advance,
Rui

**Comment by jenniening** [comment]
Hi Rui, Thanks for your interests in our package. Based on the error message you provide, it seems that directory for mgltools_x86_64Linux2_1.5.6 and vina are not correct. Could you check '/home/mgltools_x86_64Linux2_1.5.6//bin/python' and '/home/vina4dv/build/linux/release//vina' to make sure you have them in the corresponding directory?

**Comment by truatpasteurdotfr** [comment]
I had the same issue from the docker file generated image.
```
[tru@sillage ~]$ singularity shell /home/tru/singularity.d/containers/deltaVinaXGB-2021-06-24-1311.sif 
Singularity> printenv|grep app
MGLPY=/app/mgltools_x86_64Linux2_1.5.6//bin/python
MGL=/app/mgltools_x86_64Linux2_1.5.6/
PATH=/opt/conda/envs/DXGB/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/msms/:/app/mgltools_x86_64Linux2_1.5.6/bin/
DXGB=/app/DXGB
MGLUTIL=/app/mgltools_x86_64Linux2_1.5.6//MGLToolsPckgs/AutoDockTools/Utilities24/
VINADIR=/app/vina4dv-master/build/linux/release
Singularity> cp -r /app/Test_2al5 /dev/shm/
Singularity> python $DXGB/run_DXGB.py --runfeatures --datadir /dev/shm/Test_2al5 --pdbid 2al5 --average 
pdb index: 2al5
file directory: /dev/shm/Test_2al5
feature will be calculated:all
output filename : score.csv
1 molecule converted
Ligand for conformation stability:2al5_ligand.mol2
Ligand for Vina, SASA, BA, ION:2al5_ligand_rename.pdb
Protein without water molecules:2al5_protein.pdb
Protein with water molecules:2al5_protein_all.pdb
Finish Input Preparation
No Consideration of Water
No Optimized Ligand
C

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2 and POPCNT instructions.

Traceback (most recent call last):
  File "/app/DXGB/run_DXGB.py", line 103, in <module>
    main()
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/DXGB/run_DXGB.py", line 43, in main
    run_features(datadir, pdbid, water_type = water, opt_type = opt, rewrite = rewrite, feature_type = featuretype)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 599, in run_features
    feature_calculation_ligand(datadir, pdbid, inlig_pdb, inlig_rdkit, inpro_pro, water_type, opt_type, rewrite, feature_type)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 522, in feature_calculation_ligand
    run_Vina_features(datadir, i, fn, inpro, inlig)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 364, in run_Vina_features
    featureVina(outfile, fn, inpro, inlig, datadir)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_vina58.py", line 58, in featureVina
    vinalist = runVina(fn,protpdbqt,ligpdbqt)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_vina58.py", line 15, in runVina
    for lines in fileinput.input("score_v1.txt"):
  File "/opt/conda/envs/DXGB/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/opt/conda/envs/DXGB/lib/python3.7/fileinput.py", line 364, in _readline
    self._file = open(self._filename, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: 'score_v1.txt'

/proc/cpuinfo:
...
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd
_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit
 wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsave
opt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave
_vmload vgif umip overflow_recov succor smca
```

**Comment by truatpasteurdotfr** [comment]
```
Singularity> $VINADIR/vina --version

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2 and POPCNT instructions.
```
so my vina is not functionnal :(

**Comment by truatpasteurdotfr** [comment]
ok cpu dependant: it works on Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, but not on AMD Ryzen 9 3900X 12-Core Processor.

**Comment by jenniening** [comment]
Hi, could you install Vina separately following the general install steps? Just make sure source your bash file after you make change of the bash file and test Vina to see if it's working or not. Thanks! Meanwhile, I will check the docker installation during the weekend.

**Comment by truatpasteurdotfr** [comment]
yes sure!

**Comment by truatpasteurdotfr** [comment]
none of the vina prebuilt executable are suitable on my machine... 
```
vina4dv/build/linux/release/vina*
```
all exits with `Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2 and POPCNT instructions.`

According to the makefile, they were built with the intel compilers with explicit required cpus flags... :( not portable at all.
```
icpc  -ansi -Wno-long-long -O3 -DNDEBUG -O3 -fPIC -unroll -ip -axavx -xsse4.2 -openmp -vec-report -par-report -openmp-report -Wno-deprecated  ...
```

**Comment by truatpasteurdotfr** [comment]
time permitting, I will try to rebuild the vina part and report here.

**Comment by truatpasteurdotfr** [comment]
I still have access to a Centos 6.9 with boost version 1.41,0-28.el6  packages installed and intel compilers so I have rebuild the vina* executables with the following flags:
```
-O3 -DNDEBUG -fPIC -unroll -ip -axSSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,CORE-AVX2,CORE-AVX-I -openmp -vec-report -par-report -openmp-report -Wno-deprecated
```
which should work on any cpus.

**Comment by truatpasteurdotfr** [comment]
vina rebuilding fixed my issue, but the failure is a liitle farther. I am starting a new issue.

**Comment by jenniening** [comment]
NO further response

**Comment by mglgc** [comment]
> I still have access to a Centos 6.9 with boost version 1.41,0-28.el6 packages installed and intel compilers so I have rebuild the vina* executables with the following flags:
> 
> ```
> -O3 -DNDEBUG -fPIC -unroll -ip -axSSE2,SSE3,SSSE3,SSE4.1,SSE4.2,AVX,CORE-AVX2,CORE-AVX-I -openmp -vec-report -par-report -openmp-report -Wno-deprecated
> ```
> 
> which should work on any cpus.

Dear Quang Tru Huynh,
At present I'm running the same issue as you described with the docker image. Please, could you be so kind to send me that vina executable you rebuilt for all cpu compatibility? Thank you very much in advance for your reply.

**Comment by mglgc** [comment]
@truatpasteurdotfr 
Dear Quang Tru Huynh,
At present I'm running the same issue as you described with the deltaVinaXGB docker image. Please, could you be so kind to send me that vina executable you rebuilt for all cpu compatibility? Thank you very much in advance for your reply.

**Comment by truatpasteurdotfr** [comment]
https://tru.pages.pasteur.fr/static-pages/deltaVinaXGB/README.txt contains the links to the compiled binaries I have produced.
