### ISSUE TITLE
docker image converted to singularity test failure

### ISSUE THREAD

**Issue by truatpasteurdotfr** [jenniening/deltaVinaXGB#6]
```
Singularity> python $DXGB/run_DXGB.py --runfeatures --datadir /tmp/Test_2al5 --pdbid 2al5 --average 
pdb index: 2al5
file directory: /tmp/Test_2al5
feature will be calculated:all
output filename : score.csv
1 molecule converted
Ligand for conformation stability:2al5_ligand.mol2
Ligand for Vina, SASA, BA, ION:2al5_ligand_rename.pdb
Protein without water molecules:2al5_protein.pdb
Protein with water molecules:2al5_protein_all.pdb
Finish Input Preparation
No Consideration of Water
No Optimized Ligand
C
Finish Vina
1.1
SASA failed
Traceback (most recent call last):
  File "/app/DXGB/run_DXGB.py", line 103, in <module>
    main()
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/DXGB/run_DXGB.py", line 43, in main
    run_features(datadir, pdbid, water_type = water, opt_type = opt, rewrite = rewrite, feature_type = featuretype)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 599, in run_features
    feature_calculation_ligand(datadir, pdbid, inlig_pdb, inlig_rdkit, inpro_pro, water_type, opt_type, rewrite, feature_type)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 528, in feature_calculation_ligand
    run_SASA_features(datadir, i, fn, inpro, inlig)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_features.py", line 383, in run_SASA_features
    cal_SASA(out_SASA,fn,inlig,inpro,datadir)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/cal_sasa.py", line 26, in cal_SASA
    sasa_features = sasa(datadir,pro,lig)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 219, in __init__
    self.rawdata, self.rawdata_pro, self.rawdata_lig, self.sasa, self.sasa_pro, self.sasa_lig = featureSASA( self.datadir, self.prot, self.lig)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 149, in featureSASA
    df,df_pro,df_lig = runMSMS(inprot, inlig, datadir)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/featureSASA.py", line 103, in runMSMS
    tmp1 = np.genfromtxt('p_sa.area', skip_header=1)[:,2]
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1793, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/conda/envs/DXGB/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: p_sa.area not found.
```

docker image available at docker://registry-gitlab.pasteur.fr/tru/deltavinaxgb:Light

**Comment by jenniening** [comment]
Not sure how to solve this

**Comment by jenniening** [comment]
The issue is for SASA calculation and it actually related to msms. Could you check if msms has been successfully installed? You can also follow the installation step I provide for msms as shown below:

**Install msms**
``` mkdir msms 
tar -xvzf msms_i86_64Linux2_2.6.1.tar.gz -C msms 
cd msms 
cp msms.x86_64Linux2.2.6.1 msms 
```
In msms folder, there is a script pdb_to_xyzr. Change the line numfile = "./atmtypenumbers" to be numfile = "YourPATHofddeltaVinaXGB/DXGB/atmtypenumbers". atmtypenumbers file we used can be found in deltaVinaXGB/DXGB directory

**Test pdb_to_xyzr**

```pdb_to_xyzr 1crn.pdb > 1crn.xyzr```
If it doesn't work, try

```./pdb_to_xyzr 1crn.pdb > 1crn.xyzr```
If error (nawk: command not found) appears, change nawk to awk in pdb_to_xyzr (line 31)

**Comment by truatpasteurdotfr** [comment]
Hi, 
the issue for me was the prebuilt executables from https://github.com/chengwang88/vina4dv/archive/master.zip
cf  https://gitlab.pasteur.fr/tru/deltaVinaXGB/-/commit/77d1dd822bc318e3bebf347c5a2b623f8e540641

I have rebuilt it for my old cpus and everything is now fine.

Best regards

Tru
